package fr.kemstormy.discord.enums;

public enum EMatchAction {
    CLEARANCE, SHORT_CLEARANCE, SHORT_BACK_PASS, SHORT_PROGRESSIVE_PASS, LONG_PASS, SHORT_SHOT, LONG_SHOT, PENALTY, DIRECT_FREEKICK, INDIRECT_FREEKICK, CORNER, END_OF_ACTION;
}
